### ISSUE TITLE
No file outputted

### ISSUE THREAD

**Issue by nealoke** [Punk-UnDeaD/node-sass-export#1]
Hi, i'm wondering why there is no file output with the following code:

```
gulp.task('sassToJSON', function(){
	return gulp.src(paths.styles.src + 'initializers/variables.scss')
		.pipe(sass({
			functions: sassExport('testfile.js')
		}));
});
```

**Comment by Punk-UnDeaD** [comment]
plz, show me your scss file

**Comment by nealoke** [comment]
@Punk-UnDeaD Thanks for helping :) [this is a gist of my scss file](https://gist.github.com/nealoke/22e3c2b59d4e9c4aa8545ca61659b610), I need to have all these sass maps available in js.

**Comment by nealoke** [comment]
@Punk-UnDeaD Any news on this? :)

**Comment by Punk-UnDeaD** [comment]
i don't see in you code command for output anythind data

use something like 
``` $breakpoints: export('lib/breakpoints.json', $breakpoints); ```

**Comment by nealoke** [comment]
@Punk-UnDeaD is this in the _scss file_ or the _gulpfile_? 

Could you provide a full example (scss / gulpfile) just so I can understand? :) Thanks for the help!

**Comment by Punk-UnDeaD** [comment]
https://github.com/d-f-d/donetsk/blob/master/themes/yat/gulpfile.js#L23
https://github.com/d-f-d/donetsk/blob/master/themes/yat/scss/styles.scss#L20

**Comment by nealoke** [comment]
@Punk-UnDeaD This works for variables but not for sass maps, it gives me the following error trying this with my sass map (see my scss gist - $colors):

```
Message:
    ..\src\dashboard\styles\initializers\variables.scss
Error: error in C function export: a.getKey(...).getValue is not a function

       Backtrace:
        ../src/dashboard/styles/initializers/variables.scss:70, in function `export`
        ../src/dashboard/styles/initializers/variables.scss:70
        on line 70 of ../src/dashboard/styles/initializers/variables.scss
>>      $exportcolors: export('testingexport.js', $colors, (prefix:'var testme = ', s
   ----------------^
```

**Comment by nealoke** [comment]
@Punk-UnDeaD Any updates? :)

**Comment by Punk-UnDeaD** [comment]
[test.tar.gz](https://github.com/Punk-UnDeaD/node-sass-export/files/741616/test.tar.gz)
try start from this code

**Comment by nealoke** [comment]
This helped me a lot! One question, is it possible to add dependencies like `bourbon'` before you export it to json via your function?

**Comment by Punk-UnDeaD** [comment]
Yep, you can add anything to your scss.
node-sass-export only export variables and can be used as part of your global scss file with any import.

**Comment by nealoke** [comment]
@Punk-UnDeaD Thank you ;) also does your function expect sass map values to be quoted?

**Comment by nealoke** [comment]
@Punk-UnDeaD there seems to be a problem when these values are not within qoutes. That's when I get the error message. Any way to fix this issue? :)

**Comment by nealoke** [comment]
@Punk-UnDeaD nevermind, I thought that sass required unqouted map keys but it doesn't, thank you soooo much for your time! 🥇
