### ISSUE TITLE
Any way to output hex colors as hex strings?

### ISSUE THREAD

**Issue by Josh68** [Punk-UnDeaD/node-sass-export#2]
Thanks for this nifty tool. Works great with my color maps, but the output is rgb/a strings, even if the input is in hex. I dug into the docs and sass color functions, and just found `to_s`, aka `to_sass`, but I can't run this on the color object that's passed through your script. Is there any way to pipe it back out as a hex string? If so, could the tool take an option to try to output colors as hex strings? If not, please just close this issue.

**Comment by pcate-coreonyx** [comment]
I've run into the same issue with exporting Sass color variables. Would love to find a solution.

**Comment by Punk-UnDeaD** [comment]
@Josh68 , @pcate-fls , sorry for long silence and thank for good idea
